
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : LPAREN operator RPAREN\n                  | LPAREN negative RPAREN\n                  | NUMBERoperator : PLUS expression expression\n                | MINUS expression expression\n                | TIMES expression expression\n                | DIVIDE expression expressionnegative : MINUS expression'
    
_lr_action_items = {'LPAREN':([0,3,6,7,8,9,10,11,12,13,14,15,],[2,-3,2,2,2,2,-1,-2,2,2,2,2,]),'NUMBER':([0,3,6,7,8,9,10,11,12,13,14,15,],[3,-3,3,3,3,3,-1,-2,3,3,3,3,]),'$end':([1,3,10,11,],[0,-3,-1,-2,]),'PLUS':([2,],[6,]),'MINUS':([2,],[7,]),'TIMES':([2,],[8,]),'DIVIDE':([2,],[9,]),'RPAREN':([3,4,5,10,11,13,16,17,18,19,],[-3,10,11,-1,-2,-8,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,7,8,9,12,13,14,15,],[1,12,13,14,15,16,17,18,19,]),'operator':([2,],[4,]),'negative':([2,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN operator RPAREN','expression',3,'p_expression','parser.py',33),
  ('expression -> LPAREN negative RPAREN','expression',3,'p_expression','parser.py',34),
  ('expression -> NUMBER','expression',1,'p_expression','parser.py',35),
  ('operator -> PLUS expression expression','operator',3,'p_operator','parser.py',40),
  ('operator -> MINUS expression expression','operator',3,'p_operator','parser.py',41),
  ('operator -> TIMES expression expression','operator',3,'p_operator','parser.py',42),
  ('operator -> DIVIDE expression expression','operator',3,'p_operator','parser.py',43),
  ('negative -> MINUS expression','negative',2,'p_negative','parser.py',55),
]
